# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData
from enum import IntEnum


class AimIKType(IntEnum):
    None_ = 0
    OneHandRight = 1
    OneHandLeft = 2
    TwoHandRight = 3
    TwoHandLeft = 4
    Tripod = 5
    Dual = 6
    Max = 7
