# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData
from enum import IntEnum


class BulletType(IntEnum):
    Normal = 0
    Pierce = 1
    Explosion = 2
    Siege = 3
    Mystic = 4
    None_ = 5
    Sonic = 6
