# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData
from enum import IntEnum


class ProductionStep(IntEnum):
    ToDo = 0
    Doing = 1
    Complete = 2
    Release = 3
