# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData
from enum import IntEnum


class ScenarioCharacterShapes(IntEnum):
    None_ = 0
    Signal = 1
    BlackSilhouette = 2
    Closeup = 4
    Highlight = 8
    WhiteSilhouette = 16
