# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData
from enum import IntEnum


class SquadType(IntEnum):
    None_ = 0
    Main = 1
    Support = 2
    TSS = 3
