# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData
from enum import IntEnum


class StatLevelUpType(IntEnum):
    Standard = 0
    Premature = 1
    LateBloom = 2
    Obstacle = 3
    TimeAttack = 4
