# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData
from enum import IntEnum

class TacticRole(IntEnum):
    None_ = 0
    DamageDealer = 1
    Tanker = 2
    Supporter = 3
    Healer = 4
    Vehicle = 5
